### ISSUE TITLE
project is not working.

### ISSUE THREAD

**Issue by Backendeng** [baba-s/ugui-super-scrollview-example#2]
Hi,

How are you?

This project is not working on my computer. 

What package should I add?

Thanks.

**Comment by baba-s** [comment]
@Backendeng  Hi, 

This repository is a sample of the following paid assets
You will need to purchase it and add it to your project. 🙇‍♂️ 

https://assetstore.unity.com/packages/tools/gui/ugui-super-scrollview-86572
